# Generated by Django 4.1.7 on 2023-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=2, upload_to='book_images/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
