# Generated by Django 4.1.7 on 2023-03-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_author_biography_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
